data_name: gl3d_train
rawdata_dir: raw_images
feature_dump_dir: features
dataset_dump_dir: dataset
pairs_per_seq: 1000
dump_train: True
dump_valid: True
check_desc: True
exclude_seq:  []
num_process: 1
angle_th: [3,60]
overlap_th: [0.1,0.5]
corr_th: 5
incorr_th: 10
min_corr: 25
min_incorr: 10

extractor:
  name: sp #root or sp
  num_kpt: 500
  resize: [-1] 
  overwrite: True
  extract: True
  num_process: 1
  det_th: 0.00001
