data_name: scannet
rawdata_dir: scannet_eval
feature_dump_dir: scannet_test_root
dataset_dump_dir: scannet_test_root

extractor:
  name: root #root or sp
  num_kpt: 2000
  resize: [480,640]
  overwrite: False
  extract: True
  num_process: 4
  det_th: 0.00001