reader:
  name: standard
  rawdata_dir: yfcc_rawdata
  dataset_dir: yfcc_test_root/yfcc_root_2000.hdf5
  num_kpt: 2000

matcher:
  name: NN
  mutual_check: False
  ratio_th: 0.8

evaluator:
  name: AUC
  rescale: 1600
  num_pair: 4000
  inlier_th: 0.005

